-- Create the 'memory' table for storing chat history / memory
create table public.memory (
  id bigint generated by default as identity primary key,
  session_id text not null, 
  message jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add an index on session_id for fast lookups (critical for memory retrieval)
create index memory_session_id_idx on public.memory (session_id);

-- Optional: If you want to strictly link this to your 'auth.users' or public 'users' table, 
-- you can uncomment the line below. However, keeping it loosely coupled allows for 
-- anonymous sessions or different session ID formats (like 'user_id' + 'timestamp').
-- alter table public.memory add constraint memory_user_id_fkey foreign key (session_id) references auth.users (id) on delete cascade;

-- Enable Row Level Security (RLS)
alter table public.memory enable row level security;

-- Create a policy that allows services (or users) to read/write their own session data
-- (Adjust this policy based on how your backend connects. If using a service role key from n8n, this is not strictly needed, but good for safety).
create policy "Allow read access for own session"
  on public.memory
  for select
  using (true); -- CAUTION: efficient memory usually requires the backend (n8n) to have full access. Restrict if exposing to frontend.

create policy "Allow insert access"
  on public.memory
  for insert
  with check (true);
